name: notu
description: "Notu is a rethinked Note app"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  provider: ^6.1.2
  sqflite: ^2.4.2
  sqflite_common: ^2.5.5
  sqflite_common_ffi: ^2.3.5
  squadron: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  squadron_builder: ^7.1.1

flutter:
  uses-material-design: true
